language: ruby
rvm:
- 2.1.0
branches:
  only:
  - source
env:
  global:
  - secure: VA03lCgyoDTFz3Jia42Du1VEw+R4nYw8EJNQP7CqKL+ArP5fjYKAc5mZWqje4jzp642TKBKZMd2v8sl5TeQjPZtUQc/wh05wjqV+CK77VZG5Rmi+IwLlAxH9vGkweS6/v1O1s+xV4rvxKuZqgYzzfSb5zOG/N4rSrx0RWYb8Hs4=
script:
- scripts/build-ci.sh
