language: ruby
rvm:
- 2.1.0
branches:
  only:
  - source
env:
  global:
  - secure: eAfAIkapwBzL01iOQjEqvbcEr1cM1VEbohi1efcNzCkUCbJ2nsgO44tifu3vD2fJhPrDsZVfpaKXDtGD1zPFMCtMep94yUThVJl3ZEGZy8tnlZuRM/0bElDg2sRhcr9gycSJbF4zo5i/AgXF1tzcqEseIbuet+QykZj7bLHuFCo=
script:
- scripts/build-ci.sh
