language: ruby
rvm:
- 2.1.0
branches:
  only:
  - source
env:
  global:
  - secure: cuPz1NfVQzTkLZn246b1TV8Y/T3rHcq2j0o1U9E12plGRRuLRMPmeji67r3GNC5/V4Qw4mXDTgMY3X0IgicVBU+4rCBs0AUrF2Fjs2+mzTH4NOhwXF8vjt9BMTtuj+VCnZYKBR4AMjhC9SOjTbgzlwJViWkFsMreXPVvhGG7mic=
script:
- scripts/build-ci.sh
